name: fgen
description: Generate screens, viewmodels, repositories and services for/in the Flutter icapps template
version: 1.0.0
homepage: https://github.com/ikbendewilliam/flutter_commands

environment:
  sdk: '>=2.16.1 <3.0.0'

executables:
  fgen:

dependencies: 
  args: ^2.3.0
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.0

### This is just for testing purposes
fgen:
  templates_folder: .fgen
