name: fgen
description: A command-line application to generate screens, viewmodels and repositories in the Flutter icapps template
version: 0.0.1
homepage: https://github.com/ikbendewilliam/flutter_commands

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  args: ^2.3.0
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.0
